.\" generated with Ronn-NG/v0.10.1
.\" http://github.com/apjanke/ronn-ng/tree/0.10.1
.TH "GOTESTPRJTMPL" "1" "January 1980" ""
.SH "NAME"
\fBgotestprjtmpl\fR \- do something
.SH "SYNOPSIS"
\fBgotestprjtmpl\fR [\fIformat\fR\|\.\|\.\|\.] \fIfile\fR\|\.\|\.\|\.
.br
\fBgotestprjtmpl\fR \fB\-m\fR|\fB\-\-man\fR \fIfile\fR\|\.\|\.\|\.
.br
\fBgotestprjtmpl\fR \fB\-S\fR|\fB\-\-server\fR \fIfile\fR\|\.\|\.\|\.
.br
\fBgotestprjtmpl\fR \fB\-\-pipe\fR \fIfile\fR
.br
\fBgotestprjtmpl\fR < \fIfile\fR
.br
\fBgotestprjtmpl\fR \fB\-E\fR|\fB\-\-encoding\fR \fIencoding\fR \|\.\|\.\|\.
.SH "DESCRIPTION"
\fBGotestprjtmpl\fR do something\. See also help(1)\.
.P
Lorem ipsum dolor \fBsit\fR amet, consectetur adipiscing elit \fIfile\fRs file\. Donec varius lacus \fB\-\-man\fR sed lorem scelerisque dignissim\. Duis vestibulum tellus vitae quam posuere dictum\.
