[Sources.Git]
Type = "git"
VPrefix = "auto"

[Sources.VERSION]
Type = "regexp"
VPrefix = "false"
Path = "VERSION"
KeyPath = [
    "\\b(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)(-[0-9A-Za-z-]+(\\.[0-9A-Za-z-]+)*)?(\\+[0-9A-Za-z-]+(\\.[0-9A-Za-z-]+)*)?\\b"
]

